interface StreamVideoLibrary {
    Id: number,
    Name: string,
    VideoCount: number,
    TrafficUsage: number,
    StorageUsage: number,
    DateCreated: string,
    ReplicationRegions: string[],
    ApiKey: string,
    ReadOnlyApiKey: string,
    HasWatermark: boolean,
    WatermarkPositionLeft: number,
    WatermarkPositionTop: number,
    WatermarkWidth: number,
    PullZoneId: number,
    StorageZoneId: number,
    WatermarkHeight: number,
    EnabledResolutions: string,
    ViAiPublisherId: string | null,
    VastTagUrl: string | null,
    WebhookUrl: string | null,
    CaptionsFontSize: number,
    CaptionsFontColor: string,
    CaptionsBackground: string,
    UILanguage: string,
    AllowEarlyPlay: boolean,
    PlayerTokenAuthenticationEnabled: boolean,
    AllowedReferrers: string[],
    BlockedReferrers: string[],
    BlockNoneReferrer: boolean,
    EnableMP4Fallback: boolean,
    KeepOriginalFiles: boolean,
    AllowDirectPlay: boolean,
    EnableDRM: boolean,
    Bitrate240p: number,
    Bitrate360p: number,
    Bitrate480p: number,
    Bitrate720p: number,
    Bitrate1080p: number,
    Bitrate1440p: number,
    Bitrate2160p: number,
    ApiAccessKey: string,
    ShowHeatmap: boolean,
    EnableContentTagging: boolean,
    PullZoneType: null,
    CustomHTML: string,
    Controls: string,
    PlayerKeyColor: string,
    FontFamily: string,
    WatermarkVersion: number,
    EnableTranscribing: boolean,
    EnableTranscribingTitleGeneration: boolean,
    EnableTranscribingDescriptionGeneration: boolean,
    TranscribingCaptionLanguages: string[]
};

interface EditableStreamVideoLibrary {
    Name: string,
    CustomHTML: string,
    PlayerKeyColor: string,
    EnableTokenAuthentication: boolean,
    EnableTokenIPVerification: boolean,
    ResetToken: boolean,
    WatermarkPositionLeft: number,
    WatermarkPositionTop: number,
    WatermarkWidth: number,
    WatermarkHeight: number,
    EnabledResolutions: string,
    ViAiPublisherId: string,
    VastTagUrl: string,
    WebhookUrl: string,
    CaptionsFontSize: number,
    CaptionsFontColor: string,
    CaptionsBackground: string,
    UILanguage: string,
    AllowEarlyPlay: boolean,
    PlayerTokenAuthenticationEnabled: boolean,
    BlockNoneReferrer: boolean,
    EnableMP4Fallback: boolean,
    KeepOriginalFiles: boolean,
    AllowDirectPlay: boolean,
    EnableDRM: boolean,
    Controls: string,
    Bitrate240p: number,
    Bitrate360p: number,
    Bitrate480p: number,
    Bitrate720p: number,
    Bitrate1080p: number,
    Bitrate1440p: number,
    Bitrate2160p: number,
    ShowHeatmap: boolean,
    EnableContentTagging: boolean,
    FontFamily: string,
    EnableTranscribing: boolean,
    EnableTranscribingTitleGeneration: boolean,
    EnableTranscribingDescriptionGeneration: boolean,
    TranscribingCaptionLanguages: string[]
};
export default StreamVideoLibrary;
export { EditableStreamVideoLibrary };